#端口
server:
 port: 8080

#数据库连接
spring:
 datasource:
  platform: oracle
  driverClassName: oracle.jdbc.OracleDriver
  password: mdm_viewer
  #url: jdbc:oracle:thin:@10.3.5.196:1521:easorcl
  url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.3.5.196)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=easorcl)))
  username: mdm_viewer

#xml地址
#mybatis.mapper-locations=classpath:mapper/*.xml

#mybatis-plus
mybatis-plus:
 configuration:
  map-underscore-to-camel-case: true
  #在控制台打印SQL
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 mapper-locations: classpath:mapper/*.xml